# -*- MakeFile -*-

# This is which prject you are trying to make and run hSandbox or Sequoia

all:
	$(MAKE) -C Sequoia

hayden:
	$(MAKE) -C HSandBox

hayden_clean:
	$(MAKE) clean -C HSandBox

gian:
	$(MAKE) -C GSandBox

gian_clean:
	$(MAKE) clean -C GSandBox

clean:

